name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "1.20"

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: validate gradle wraper
        uses: gradle/wrapper-validation-action@v1
        
      - name: setup jdk
        uses: actions/setup-java@v3
      
      - name: make gradle wrapper executable
        uses: chmod +x ./gradlew
      
      - name: capture build artifacts
        uses: actions/upload-artifacts-@v3
      
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      
